### ISSUE TITLE
it takes 2 positional arguments but was given 3

### ISSUE THREAD

**Issue by cwoonb** [braindotai/Facial-Landmarks-Detection-Pytorch#1] opened 2021-01-21 06:52 UTC
![errors](https://user-images.githubusercontent.com/63994622/105310789-9dac4400-5c00-11eb-9e9b-c638c1b13450.PNG)

It takes 2 positional arguments but was given 3. What should I do?It takes 2 positional arguments but was given 3. What should I do?

**Comment by braindotai** [comment] 2021-01-21 06:58
Replace
```
self.landmarks_augmentation = LandmarksAugmentation(image_dim, angle)
```
with 
```
self.landmarks_augmentation = LandmarksAugmentation(angle)
```
Since `image_dim` is not required in `LandmarksAugmentation`, so I must have updated the class `LandmarksAugmentation` but forgot to update its initialization. :}

**Comment by braindotai** [comment] 2021-01-23 04:46
The solution of the issue is straight forward, so I'm closing it for now, feel free to reopen it again if required.

**Closed as completed by braindotai** 2021-01-23 04:46 UTC
